### ISSUE TITLE
Intermittent Memory access fault by GPU - Reason: Unknown.

### ISSUE THREAD

**Issue by PhilipDeegan** [ROCm-Developer-Tools/ROCclr#12]
Hi,

2 out of 5 executions are failing on my program.

This seems like a better place than my original issue: 
https://github.com/ROCm-Developer-Tools/HIP/issues/2097

Any tips to debug would be appreciated.

System
Debian 10 buster-backports / kernel 5.5
GPU VEGA 64 RX Liquid
CPU - Ryzen 3950x @ stock
Mobo - Asrock Taichi x570 @ stock
RAM - 64GB DDR4 @ 3ghz XMPP auto

**Comment by Dekken** [comment]
This seems to have been resolved by setting a non-zero sized "dynamicShared"

**Comment by PhilipDeegan** [comment]
my own fault.
