### ISSUE TITLE
HSA_AMD_SVM_ATTRIB_READ_MOSTLY missing in ROCR-Runtime headers.

### ISSUE THREAD

**Issue by v01dXYZ** [ROCm-Developer-Tools/ROCclr#26]
Hi,
I can't find the definition of HSA_AMD_SVM_ATTRIB_READ_MOSTLY in the current ROCR-Runtime repo.
Where is it ?
Thank you

**Comment by gandryey** [comment]
It should be in hsa_ext_amd.h under **typedef enum hsa_amd_svm_attribute_s {**
  // Optimizes with the anticipation that the majority of operations to the
  // range will be read operations.
  // Type of this attribute is bool.
  HSA_AMD_SVM_ATTRIB_READ_MOSTLY = 6,
The change in local repo was made 5 months ago.

**Comment by v01dXYZ** [comment]
Thank you, would you like I submit this as a patch to the ROCR-Runtime repo if it can help you ?

**Comment by gandryey** [comment]
Not sure about that. We need a proper promotion of ROCR-runtime. I'll check if it can be done in a few days.
