### ISSUE TITLE
Compling ROCclr with PAL backend: Closed source elements

### ISSUE THREAD

**Issue by v01dXYZ** [ROCm-Developer-Tools/ROCclr#27]
Hi,
I am trying to compile Roclr with PAL (BUILD_PAL cmake flag set) in order to get ROCm working on Azure instances.
Unfortunately, it seems not everything is publicly available: headers such as `glATIInternal.h`, a closed source version of `PAL` with extented structures/classes or additional enum values (Navi10_A0, Polaris22, ...).

Is there truly closed source elements or didn't I search enough ?

Anyway, is there a way  to get a half-featured ROCM working on a VM with very limited PCI features ? I focused on the PAL way because it seemed to me it could have worked anywhere a Vulkan stack could run some shaders.

**Comment by vsytch** [comment]
The Pal backend support is partially open sourced and only intended for the Windows driver. You won't be able to build it given what sources are public.

Note that the PAL repo used by AMDVLK is heavily sanitized and has OCL/HIP support stripped out.
