### ISSUE TITLE
OpenCL ICD Versions

### ISSUE THREAD

**Issue by acowley** [ROCm-Developer-Tools/ROCclr#6]
I am having trouble building ROCm-OpenCL-Runtime due to what seems to be an inconsistency in the circular dependency between that package and this one. ROCclr forward declares `KHRicdVendorDispatchRec` [here](https://github.com/ROCm-Developer-Tools/ROCclr/blob/master/platform/object.hpp#L64), but ROCclr relies upon the ROCm-OpenCL-Runtime headers which [no longer](https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/blob/master-next/khronos/icd/loader/icd_dispatch.h) provide that definition. [Older](https://github.com/KhronosGroup/OpenCL-ICD-Loader/blob/6c03f8b58fafd9dd693eaac826749a5cfad515f8/loader/icd_dispatch.h#L1282) Khronos ICDs do, but then it is not clear what ICD to build ROCm-OpenCL-Runtime against.

**Comment by AlexXAmd** [comment]
This issue should be fixed by: https://github.com/ROCm-Developer-Tools/ROCclr/pull/11

**Comment by acowley** [comment]
Thank you!
